// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA0IXYFWDqvYc1HLocscyCt-fnzpGhsGE',
    appId: '1:978340159895:web:465f127ea3a79c09fe64d2',
    messagingSenderId: '978340159895',
    projectId: 'gaming-zone-booking',
    authDomain: 'gaming-zone-booking.firebaseapp.com',
    storageBucket: 'gaming-zone-booking.firebasestorage.app',
    measurementId: 'G-WRJQP9XSS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASj2IdlVmuJEilV22Yw6Asfy6Ag8-G6Fk',
    appId: '1:978340159895:android:8dae339584316c89fe64d2',
    messagingSenderId: '978340159895',
    projectId: 'gaming-zone-booking',
    storageBucket: 'gaming-zone-booking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7W13V_jDPC37_CBtzI5G6YGAcRZXouSs',
    appId: '1:978340159895:ios:8ba24be374551e7efe64d2',
    messagingSenderId: '978340159895',
    projectId: 'gaming-zone-booking',
    storageBucket: 'gaming-zone-booking.firebasestorage.app',
    iosBundleId: 'com.example.gamingZoneBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7W13V_jDPC37_CBtzI5G6YGAcRZXouSs',
    appId: '1:978340159895:ios:8ba24be374551e7efe64d2',
    messagingSenderId: '978340159895',
    projectId: 'gaming-zone-booking',
    storageBucket: 'gaming-zone-booking.firebasestorage.app',
    iosBundleId: 'com.example.gamingZoneBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA0IXYFWDqvYc1HLocscyCt-fnzpGhsGE',
    appId: '1:978340159895:web:aae56741b1b9b5c8fe64d2',
    messagingSenderId: '978340159895',
    projectId: 'gaming-zone-booking',
    authDomain: 'gaming-zone-booking.firebaseapp.com',
    storageBucket: 'gaming-zone-booking.firebasestorage.app',
    measurementId: 'G-RPB6DZ6J5Q',
  );
}
